source 'http://rubygems.org'
ruby '2.0.0'
gem 'compass'
gem 'sinatra'
gem 'haml'
gem 'rack-cache', '~> 1.2'
gem 'newrelic_rpm', '~> 3.7.0.177'
gem 'unicorn', '~> 4.7.0'
gem 'sidekiq', '~> 2.17.1'
gem 'sidetiq', '~> 0.5.0'
gem 'sinatra-assetpack', '~> 0.3.1'
gem 'github-markup', '~> 1.0.0'
gem 'github-markdown', '~> 0.6.3'