QuantumCraft is a work in progress mod based around science and things with Quantum in the name. We plan to base the mod around a research system and an energy net too.

<h1> What does it add? </h1>

QuantumCraft adds several different Quantum machines that use Quantum Energy. You can find a list on the left. But machines aren't everything! We have many other things that you'll be sure to love. Go ahead, click on the links to the left and explore.